### ISSUE TITLE
Please allow controlling new user creations

### ISSUE THREAD

**Issue by onnyyonn** [Alt-er/obsidian-sync-share-server#1]
First of all, thank you for the Obsidian extension. Out of all the syncing extensions I have tried, yours is the closest to what I wanted.

I would like to request one feature for the backend server. Right now, anyone can create an account on the server as long as they know the URL. Would it be possible to control that somehow? I am trying to prevent a scenario where a malicious user dumps a huge amount of data on my server.

**Comment by Alt-er** [comment]
I really need a function to restrict registration, and I am going to add a simple restriction, for example: prohibit registration when a certain file exists, which may require executing a command to create the file.

Due to time reasons, some methods are more troublesome to implement, or require restarting the service to take effect, so there is no choice. I will use this method for the time being. If there are better suggestions, we can discuss them.

**Comment by onnyyonn** [comment]
> Prohibit registration when a certain file exists, which may require executing a command to create the file.

This sounds good to me. Thanks.

**Comment by Alt-er** [comment]
Already updated, please upgrade to the latest version of the server. You can use docker to quickly upgrade.

https://github.com/Alt-er/obsidian-sync-share?tab=readme-ov-file#other-configurations
